#include "Localization.h"

dictionary Localization::english = dictionary{
	{ "KEY_LANGUAGE", "Language"},
	{ "KEY_HELLO", "Hello" },
	{ "KEY_HANGMAN", "Hangman" },
	{ "KEY_PLAY", "Play" },
	{ "KEY_OPTIONS", "Options" },
	{ "KEY_QUIT", "Quit" },
	{ "KEY_YOU_LOSE", "You lose!" },
	{ "KEY_YOU_WIN", "You win!" },
	{ "KEY_ALPHABET", "ABCDEFGHIJKLMNOPQRSTUVWXYZ" },
	{ "KEY_ABBREVIATION", "EN"},
	{ "KEY_MENU", "Menu" },
	{ "KEY_CONFIRM", "Confirm" },
	{ "KEY_SAVE", "Save" },
	{ "KEY_NAME", "Name" },
	{ "KEY_VOLUME", "Volume"},
	{ "KEY_LOAD", "Load"},
	{ "KEY_CREATE", "Create"},
	{ "KEY_PROFILE", "Profile"},
	{ "KEY_SEARCH", "Search"},
	{ "KEY_FOUND", "Found"},
	{ "KEY_REVERT", "Revert"},
	{ "KEY_MATCHES", "Matches"},
	{ "KEY_WINS", "Wins"},
	{ "KEY_GUESSES", "Guesses"},
	{ "KEY_CORRECT", "Correct"},
	{ "KEY_TIME", "Time"},
	{ "KEY_PLAYED", "Played"},
	{ "KEY_SECONDS", "Seconds"},
	{ "KEY_MADE", "Made"},
	{ "KEY_TO", "To"},
	{ "KEY_CONTINUE", "Continue"},
	{ "KEY_OR", "Or"}
};

dictionary Localization::swedish = dictionary{
	{ "KEY_LANGUAGE", "Språk"},
	{ "KEY_HELLO", "Hej" },
	{ "KEY_HANGMAN", "Hänga gubben" },
	{ "KEY_PLAY", "Starta" },
	{ "KEY_OPTIONS", "Inställningar" },
	{ "KEY_QUIT", "Avsluta" },
	{ "KEY_YOU_LOSE", "Du förlorade!" },
	{ "KEY_YOU_WIN", "Du vann!" },
	{ "KEY_ALPHABET", "ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ" },
	{ "KEY_ABBREVIATION", "SE" },
	{ "KEY_MENU", "Meny" },
	{ "KEY_CONFIRM", "Bekräfta" },
	{ "KEY_SAVE", "Spara" },
	{ "KEY_NAME", "Namn" },
	{ "KEY_VOLUME", "Volym"},
	{ "KEY_LOAD", "Ladda"},
	{ "KEY_CREATE", "Skapa"},
	{ "KEY_PROFILE", "Profil"},
	{ "KEY_SEARCH", "Sök"},
	{ "KEY_FOUND", "Hittad"},
	{ "KEY_REVERT", "Ångra"},
	{ "KEY_MATCHES", "Matcher"},
	{ "KEY_WINS", "Vinster"},
	{ "KEY_GUESSES", "Gissningar"},
	{ "KEY_CORRECT", "Korrekta"},
	{ "KEY_TIME", "Tid"},
	{ "KEY_PLAYED", "Spelat"},
	{ "KEY_SECONDS", "Sekunder"},
	{ "KEY_MADE", "Gjorda"},
	{ "KEY_TO", "För att"},
	{ "KEY_CONTINUE", "Fortsätta"},
	{ "KEY_OR", "Eller"}

};
